<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro" name="ddrive">
<xacro:property name="yaml_file" value="$(find diff_drive)/ddrive.yaml" />
<xacro:property name="props" value="${xacro.load_yaml(yaml_file)}" />
<xacro:property name="start" value="${props['/**']}"/>
<xacro:property name="ros__parameters" value="${start['ros__parameters']}"/>
<xacro:property name="caster_rad" value="${ros__parameters['caster_rad']}"/>
<xacro:property name="stem_h" value="${ros__parameters['stem_h']}"/>
<xacro:property name="front_wheel_rad" value="${ros__parameters['front_wheel_rad']}"/>
<xacro:property name="rob_height" value="${ros__parameters['rob_height']}"/>
<xacro:property name="robot_width" value="${ros__parameters['robot_width']}"/>
<xacro:property name="robot_length" value="${ros__parameters['robot_length']}"/>
<xacro:property name="robot_mass" value="${ros__parameters['robot_mass']}"/>
<xacro:property name="f_wheel_len" value="${ros__parameters['f_wheel_len']}"/>
<xacro:property name="f_wheel_mass" value="${ros__parameters['f_wheel_mass']}"/>
<xacro:property name="stem_rad" value="${ros__parameters['stem_rad']}"/>
<xacro:property name="stem_mass" value="${ros__parameters['stem_mass']}"/>
<xacro:property name="caster_mass" value="${ros__parameters['caster_mass']}"/>
<xacro:property name="caster_len" value="${ros__parameters['caster_len']}"/>

  <gazebo>
    <plugin name="gazebo_ros_control" filename="libgazebo_ros_control.so">
      <robotNamespace>/ddrive</robotNamespace>
      <robotSimType>gazebo_ros_control/DefaultRobotHWSim</robotSimType>
    </plugin>
  </gazebo>

  <gazebo reference="base_link">
    <material>Gazebo/Red</material>
  </gazebo>

  <gazebo reference="right_front_wheel">
    <material>Gazebo/Blue</material>
  </gazebo>

  <gazebo reference="left_front_wheel">
    <material>Gazebo/Blue</material>
  </gazebo>

  <gazebo reference="top_stem">
    <material>Gazebo/Pink</material>
  </gazebo>

  <gazebo reference="bottom_stem">
    <material>Gazebo/Purple</material>
  </gazebo>

  <gazebo reference="top_caster">
    <material>Gazebo/Pink</material>
  </gazebo>

  <gazebo reference="bottom_caster">
    <material>Gazebo/Purple</material>
  </gazebo>

  <gazebo>
    <!-- <plugin name="ignition::gazebo::systems::DiffDrive" filename="libignition-gazebo-diff-drive-system.so"> -->
    <plugin
      name="ignition::gazebo::systems::DiffDrive"
      filename="libignition-gazebo-diff-drive-system.so">
      <left_joint>base_to_left_front_wheel</left_joint>
      <right_joint>base_to_right_front_wheel</right_joint>
      <wheel_separation>${robot_width + (f_wheel_len/2)}</wheel_separation>
      <wheel_radius>${front_wheel_rad}</wheel_radius>
      <odom_publish_frequency>1</odom_publish_frequency>
      <topic>cmd_vel</topic>
      <odom_topic>jerry_odom</odom_topic>
      <tf_topic>jerry_tf</tf_topic>
      <frame_id>jerry_odom</frame_id>
      <child_frame_id>base_link</child_frame_id>
    </plugin>
  </gazebo>

  <!-- Joint states plugin -->
  <gazebo>
    <plugin filename="libignition-gazebo-joint-state-publisher-system.so" name="ignition::gazebo::systems::JointStatePublisher"/>
  </gazebo>
</robot>