/**:
    ros__parameters:
        caster_rad: 0.025
        caster_len: 0.1
        caster_mass: 0.01
        stem_h: 0.05
        stem_rad: 0.02
        stem_mass: 0.001
        front_wheel_rad: 0.12
        f_wheel_len: 0.1
        rear_wheel_rad: 0.12
        r_wheel_len: 0.1
        f_wheel_mass: 0.1
        r_wheel_mass: 0.1
        rob_height: 0.1
        robot_width: 0.3
        robot_length: 0.7
        robot_mass: 1.0
